### ISSUE TITLE
Add support for Flight Availabilities Search API

### ISSUE THREAD

**Issue by tsolakoua** [amadeus4dev/amadeus-java#101]
https://developers.amadeus.com/self-service/category/air/api-doc/flight-availabilities-search/api-reference

**Comment by davem-ec** [comment]
Are we missing something? Is there another end point for flight availbility? 

Any eta on this API?

**Comment by davem-ec** [comment]
I see that there is the ability to directly specify the endpoint, so that is a work around.

Thanks for the effort here!

**Comment by tsolakoua** [comment]
This issue refers to the support of the API in the Java SDK. Of course, the Java SDK supports arbitrary calls as described in the README so any API call be called from the Java SDK if the developer uses the right method, URL and body.
