### ISSUE TITLE
No emailAddress field available for com.amadeus.resources.Traveler.Contact class

### ISSUE THREAD

**Issue by 1hamidreza** [amadeus4dev/amadeus-java#118]
Hi,

Based on the provided API Document for Flight Create Orders the com.amadeus.resources.Traveler.Contact class suppose to have emailAddress variable which is not there :

![image](https://user-images.githubusercontent.com/14147824/142464557-577517cb-2252-4f26-9631-8668533b5dd2.png)

I believe it needs to be added as String variable.

_Hamid

**Comment by tsolakoua** [comment]
Thanks!

**Comment by 1hamidreza** [comment]
@tsolakoua Thanks to you. Can we have a new release to have the changes applied ?

**Comment by tsolakoua** [comment]
New [release](https://github.com/amadeus4dev/amadeus-java/releases/tag/v5.8.2) done @1hamidreza :)
