### ISSUE TITLE
testBuilderWithInvalidEnvironment test fails

### ISSUE THREAD

**Issue by alnacle** [amadeus4dev/amadeus-java#12]
com.amadeus.AmadeusTest > testBuilderWithInvalidEnvironment FAILED
    java.lang.AssertionError

86 tests completed, 1 failed

FAILURE: Build failed with an exception.

**Comment by jabrena** [comment]
This thread could be interesting:
https://stackoverflow.com/questions/8168884/how-to-test-code-dependent-on-environment-variables-using-junit

```java
  @Test
  public void testBuilderWithInvalidEnvironment() {
    Map<String,String> environment = new HashMap<String, String>();//System.getenv();
    environment.put("AMADEUS_CLIENT_ID", "DEMO");
    environment.put("AMADEUS_CLIENT_SECRET", "DEMO");
    assertTrue(Amadeus.builder(environment).build() instanceof Amadeus,
        "should return a Configuration");
  }
```

I will review in coming days, how to inject a Environment variables in a Unit Test.

Juan Antonio

**Comment by jabrena** [comment]
Added PR:
https://github.com/amadeus4dev/amadeus-java/pull/155
