### ISSUE TITLE
integrating soap Enterprise API

### ISSUE THREAD

**Issue by shrirangsalokhe09** [amadeus4dev/amadeus-java#128]
## Description

I am trying to integrate Amadeus SOAP enterprise web services using  Java. How to call and make headers 4.0 and requests in Java?
Any prerequisite jar provided to create header and to call services?

**Comment by shrirangsalokhe09** [comment]
please provide steps to integrate soap API from given WSDL file? and if example available will be helpful.

**Comment by tsolakoua** [comment]
This Java library is built for the Amadeus Self-Service travel APIs. For the integration of the Enterprise APIs we suggest you to get in touch directly with your dedicated account manager.
