### ISSUE TITLE
Clean old branches in repository

### ISSUE THREAD

**Issue by jabrena** [amadeus4dev/amadeus-java#145]
## Description

Clean old branched in the repository:
https://github.com/amadeus4dev/amadeus-java/branches/stale

**Comment by xianqiliu** [comment]
Hey @tsolakoua , maybe this issue should be closed? Cuz I saw there's no old branch in this repo :)

**Comment by tsolakoua** [comment]
True, I forgot to close it :) thanks @xianqiliu
