### ISSUE TITLE
Remove the duplicate version 

### ISSUE THREAD

**Issue by anthonyroux** [amadeus4dev/amadeus-java#15]
## Description

We are managing the version at 2 different places:
1 in the Amadeus constant file 
1 in the gradle file

It's painful when releasing a new version to update both (+ the unit test)

**Comment by SealSoft** [comment]
Hey, I think i got a solution for this duplication issue. Already created an new branch into my forked repo using a `FileInputSteam` in order to get version name from `gradle.properties` file.

I can create a pull request

**Comment by anthonyroux** [comment]
Hey @SealSoft that would be great! Please open the PR and our team will do the review :).

Thanks a lot!

**Comment by jabrena** [comment]
Added a solution at pipeline level.
The solution is working with no change in the library.
https://github.com/amadeus4dev/amadeus-java/pull/154
