### ISSUE TITLE
Add airline name to flight-offer payload

### ISSUE THREAD

**Issue by steve-donovan** [amadeus4dev/amadeus-java#190]
## Description

Currently, the flight-offer JSON structure only returns the airline IATA code for each itinerary segment. It would be better to also include the airline name for the consumer's benefit. I guess the logo would be pushing it? :)

## Steps to Reproduce

1. Make a call to flight offers search API
2. Examine the returned JSON payload

<img width="518" alt="Screenshot 2022-08-09 at 11 58 01" src="https://user-images.githubusercontent.com/106157038/183632198-54de09bd-5245-4220-b7fa-e426699e79c0.png">

**Comment by jabrena** [comment]
Hi @steve-donovan, 

can you provide the `curl` request about your previous response?

Juan Antonio

**Comment by steve-donovan** [comment]
> Hi @steve-donovan,
> 
> can you provide the `curl` request about your previous response?
> 
> Juan Antonio

not curl as I'd need to supply my private token, but this is the GET - hope that's ok

https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=SYD&destinationLocationCode=BKK&departureDate=2022-11-01&adults=1

**Comment by steve-donovan** [comment]
Could we also add airport name whilst you're in the same code area? The addition of both would be much more convenient for the consumer

<img width="560" alt="Screenshot 2022-08-16 at 08 52 38" src="https://user-images.githubusercontent.com/106157038/184827738-236633db-a6d1-4763-bcc7-cad31d8ba376.png">
r

**Comment by jabrena** [comment]
Hi @steve-donovan,

Sorry the delay, but yesterday it was Bank holiday in Spain & France.

In relation to your question:

```
ACCESS_TOKEN=$(curl -H "Content-Type: application/x-www-form-urlencoded" \
https://test.api.amadeus.com/v1/security/oauth2/token \
-d "grant_type=client_credentials&client_id=$AMADEUS_CLIENT_ID&client_secret=$AMADEUS_CLIENT_SECRET" \
| grep access_token | sed 's/"access_token": "\(.*\)"\,/\1/' | tr -d '[:space:]')
echo $ACCESS_TOKEN
curl -X GET "https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=SYD&destinationLocationCode=BKK&departureDate=2022-11-01&adults=1" \
-H "Authorization: Bearer $ACCESS_TOKEN" -k
``` 

Your request is not possible to be resolved, in this project we develop a client to interact with the API but the request is developed in another areas of Amadeus. You should process the JSON the given format.

Juan Antonio

**Comment by Yusasif-AI** [comment]
> ## Description
> Currently, the flight-offer JSON structure only returns the airline IATA code for each itinerary segment. It would be better to also include the airline name for the consumer's benefit. I guess the logo would be pushing it? :)
> 
> ## Steps to Reproduce
> 1. Make a call to flight offers search API
> 2. Examine the returned JSON payload
> 
> <img alt="Screenshot 2022-08-09 at 11 58 01" width="518" src="https://user-images.githubusercontent.com/106157038/183632198-54de09bd-5245-4220-b7fa-e426699e79c0.png">

HI, where you able to solve this?
I am having the same issue?
