### ISSUE TITLE
Rename flight-offer oneWay element

### ISSUE THREAD

**Issue by steve-donovan** [amadeus4dev/amadeus-java#191]
## Description

The element name doesn't accurately describe its true purpose. Maybe combinableOneWay would be better naming choice?

## Steps to Reproduce

1. Make a call to flight offers search API
2. Examine the returned JSON payload

![image](https://user-images.githubusercontent.com/106157038/183672319-ca14ce3f-ed42-4d5f-8501-ffaf26e6e44d.png)

**Comment by jabrena** [comment]
As I commented, it is complicated to change the design in the short term.
In your travel application, you will have to be integrated with current JSON response.
