### ISSUE TITLE
com.amadeus.resources.Traveler has inconsistencies between constructors 

### ISSUE THREAD

**Issue by steve-donovan** [amadeus4dev/amadeus-java#196]
## Description

1. **Traveler** constructor only sets a subset of the class members even though all are provided in the method signature.
```
  public Traveler(String id, String dateOfBirth, String gender,
      Name name, Contact contact, Document[] documents) {
    this.name = name;
    this.contact = contact;
  }
```

2. **Traveler.Contact** parameterized constructor has no body
```
    public Contact(Phone phones, String emailAddress) {
    }
```

3. **Traveler.Document** parameterized constructor has no body
```
    public Document(String documentType, String number, String expiryDate, 
        String issuanceCountry, String nationality, boolean holder) {

    }
```

4. **Traveler.Phone** parameterized constructor has no body
```
    public Phone(String countryCallingCode, String number) {
    }
```

Should I add appropriate bodies, drop the parameterized constructors completely and rely on setter usage? What are the mandatory fields, and how to enforce them if only using setters -rely purely on marshaling?

Let me know and I'll raise a PR.

**Comment by jabrena** [comment]
Hi @steve-donovan.

good review, go ahead with the PR.

Juan Antonio

**Comment by jabrena** [comment]
I will review the class and I will say something tomorrow.

Where is you come from?
here, it is 15:00 CEST

and you?

**Comment by steve-donovan** [comment]
Thanks @jabrena 
I'm from UK , and there visiting family at the mo, but i actually live in France currently. I recently read about a new digital nomad visa for bali - 5 years and tax free . So i may say goodbye to france 😊

**Comment by jabrena** [comment]
I will help you but please, share a pic from Bali one day! :p 

I reviewed the class and honestly, we need to do some changes:

- https://github.com/amadeus4dev/amadeus-java/blob/master/src/main/java/com/amadeus/resources/Traveler.java
- https://github.com/amadeus4dev/amadeus-java/blob/master/src/main/java/com/amadeus/resources/FlightOrder.java
- https://github.com/amadeus4dev/amadeus-code-examples/blob/master/flight_create_orders/v1/post/Java%20SDK/FlightCreateOrders.java

**Comment by steve-donovan** [comment]
hahaha happily

oh yes i see - that's a little bit ugly. Looks like some debt between Traveler and FlightOrder.Traveler.

ok talk later. thanks.

**Comment by tsolakoua** [comment]
Thanks for reporting the issue @steve-donovan, I will check it out as well and create a PR soon.
