### ISSUE TITLE
hotel price search convenience endpoint

### ISSUE THREAD

**Issue by steve-donovan** [amadeus4dev/amadeus-java#209]
## Description

How do you feel about a convenience endpoint which gets the hotel list for a location, with the prices? Currently, it's a 2-step process, the API consumer has to first call an endpoint to get a list of hotels for a location, just to use the hotel codes as params for a second call to get prices and availability. I can't really imagine a scenario where step 1 is useful when it returns such limited information. Please educate me if I'm missing the point.

I'm happy to raise PR as I could make use of such an endpoint.

**Comment by jabrena** [comment]
Hi @steve-donovan sorry the delay, 

Can you share the methods that you are using currently for this particular question?

Juan Antonio

**Comment by steve-donovan** [comment]
Hi @jabrena 
No problem.
1. retrieve hotel list for desired destination `amadeus.referenceData.locations.hotels.byCity`
2. use the id's from 1. to retrieve pricing information `amadeus.shopping.hotelOffers`

**Comment by jabrena** [comment]
This kind of libraries are designed to provide the building blocks to interact with all Amadeus Self Service APIs but it doesn't provide solutions combining calls from one api to another one, this is part of the User's journey.
