### ISSUE TITLE
Bug in Android  

### ISSUE THREAD

**Issue by vht210** [amadeus4dev/amadeus-java#21]
## Description
When I try to use the library in Android App. I have noticed that it always send POST request instead of GET request.
The reason is under com.amadeus/Request.java you have
protected void establishConnection() throws IOException {
    this.connection = (HttpURLConnection) new URL(uri).openConnection();
    connection.setRequestMethod(verb);
    connection.setDoInput(true);
    connection.setDoOutput(true);
   
So no matter setRequestMethod is, when setDoOutput=true, it always POST 

According to https://developer.android.com/reference/java/net/HttpURLConnection
HTTP Methods
HttpURLConnection uses the GET method by default. It will use POST if setDoOutput(true) has been called. Other HTTP methods (OPTIONS, HEAD, PUT, DELETE and TRACE) can be used with setRequestMethod(String).

Suggestion fix:
connection.setDoOuput(true) only when the verb is POST

**Comment by anthonyroux** [comment]
I've been able to reproduce, added to our backlog to fix it.

Thank you very much!

**Comment by anthonyroux** [comment]
I published the fix under the 3.0.1 version.
It has been released on Bintray, it always takes longer to have it available on JCenter.

Thanks a lot for your contribution!
