### ISSUE TITLE
Update params to accept String array as input 

### ISSUE THREAD

**Issue by tsolakoua** [amadeus4dev/amadeus-java#215]
Some APIs get an array of Strings as input, but the SDK works only with Strings and causes an exception when array is passed. It's related to https://github.com/amadeus4dev/amadeus-java/issues/211.

The following APIs accept array[string] as parameters:

- Hotel Search 1st endpoint. Params: `hotelIds`
- Hotel List by hotels. Params: `hotelIds`
- Hotel List by-city. Params: `amenities`
- Hotel List by geocode. Params: `amenities`
- Hotel Ratings. Params: `hotelIds`
- Hotel Name autocomplete. Params: `subType`
- Points of Interest 1st and 2nd endpoint. Params: `category` 
- Airport & City Search. Params: `subType`
- City Search. Params: `include`

**Comment by Sprokof** [comment]
Hi, does this issue still actually? If so i would like to work on this

**Comment by tsolakoua** [comment]
Hello @Sprokof, the issue is still valid. Thanks :)
