### ISSUE TITLE
Add support for Trip Parser API

### ISSUE THREAD

**Issue by anthonyroux** [amadeus4dev/amadeus-java#28]
Support for [Trip Parser](https://developers.amadeus.com/self-service/category/trip/api-doc/trip-parser/api-reference) v3.

**Comment by tsolakoua** [comment]
https://github.com/amadeus4dev/amadeus-java/pull/59

**Comment by siddharthapdutta** [comment]
Hi @tsolakoua!
A solution could be to send a File instance to a TripParser client's post() method which in turn Base64 encodes the file contents and sends it to the API. (Similar to the Python SDK) I've tested this approach and it seems to be working. 
If this is acceptable, I can create a PR for Trip Parser support.
