### ISSUE TITLE
Add support for Flight Create Orders API

### ISSUE THREAD

**Issue by anthonyroux** [amadeus4dev/amadeus-java#32]

**Comment by pallerana** [comment]
Am interested in contributing to this project and I'd like to know more about this issue, can you please provide more description of this issue, so that I can take a look at it

**Comment by anthonyroux** [comment]
Hi @pallerana, thanks a lot for contacting us. We will be very happy to have your contribution.
Flight Create Orders is not the easiest API to start with, I will advise taking a look at the issue:
https://github.com/amadeus4dev/amadeus-java/issues/42 which is easier. You can get inspiration of what we did in our Python SDK for the same API: https://github.com/amadeus4dev/amadeus-python/pull/54/files

Don't hesitate to contact us if you face any issue.

Cheers,
Anthony
