### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Traveeee** [amadeus4dev/amadeus-java#46]
## Description

[Describe the issue]
I have integrated the hotel search API successfully to my website but I keep getting 1 image per hotel, how can I get more images per hotel? 
## Steps to Reproduce

1. [First step]
2. [Second step]
3. [and so on...]

__Expected Behavior:__ [What you expect to happen]

__Actual Behavior:__ [What actually happens]

__Stable Behavior?__ [What percentage of the time does it reproduce?]

## Versions

[What version of Java/JVM are you running? What Operating System are you on?]

## Checklist

Please make sure you checked the following:

* Did you download the latest version of this library?

**Comment by anthonyroux** [comment]
Are you using the API in production or in test?

**Comment by Traveeee** [comment]
@anthonyroux Production, but self-service.

**Comment by anthonyroux** [comment]
https://stackoverflow.com/questions/60167395/how-to-get-all-images-for-a-given-hotel-using-self-service-amadeus-api
