### ISSUE TITLE
SOAP Amadeus APISin Java

### ISSUE THREAD

**Issue by Gaurav191** [amadeus4dev/amadeus-java#77]
## Description

[Describe the issue]

## Steps to Reproduce

1. [First step]
2. [Second step]
3. [and so on...]

__Expected Behavior:__ [What you expect to happen]

__Actual Behavior:__ [What actually happens]

__Stable Behavior?__ [What percentage of the time does it reproduce?]

## Versions

[What version of Java/JVM are you running? What Operating System are you on?]

## Checklist

Please make sure you checked the following:

* Did you download the latest version of this library?

**Comment by anthonyroux** [comment]
Hi, For the SOAP APIs (Enterprise APIs) you need to contact your account manager. This GitHub organization is dedicated to [Self-Service APIs](https://developers.amadeus.com/self-service).

**Comment by Gaurav191** [comment]
Okay Thanks for you reply.

**Comment by Gaurav191** [comment]
Yeah done implementation in Java
