### ISSUE TITLE
How to add an OSI remark for Emirate Airline

### ISSUE THREAD

**Issue by nicoclau** [amadeus4dev/amadeus-java#82]
Hello we need to update our pnrs with 

"OSI EK DFNT"

so we can confirm the booking with emirate,
can you please tell us how to add the OSI please ?

Thanks for your help
Kind regards
Nicolas

**Comment by anthonyroux** [comment]
It seems you are an Enterprise user. This SDK is made for Self-Service REST/JSON APIs only.

Please contact your account manager for any questions related to the Enterprise APIs.
