### ISSUE TITLE
safetyRatedLocations does not return any safetyRatings

### ISSUE THREAD

**Issue by jvence** [amadeus4dev/amadeus-java#85]
safetyRatings is always null in the results (these lat,lng returns results in the sandbox):

`Amadeus amadeus = Amadeus.builder("[hidden]", "[hidden]").build();
		try {
			SafePlace[] safetyScore = amadeus.safety.safetyRatedLocations
					.get(Params.with("latitude", 51.50735).and("longitude", -0.12775));
			System.out.println();
		} catch (ResponseException e) {
                     e.printStackTrace();
		}`

using 
<dependency>
  <groupId>com.amadeus</groupId>
  <artifactId>amadeus-java</artifactId>
  <version>5.3.0</version>
</dependency>

**Comment by jvence** [comment]
Seems like   private @Getter SafetyRating safetyRating; should be   private @Getter SafetyRating safetyScores; instead (as that is what is returned by the rest call)

**Comment by tsolakoua** [comment]
Hello @jvence , thank you very much for identifying the bug. It has already been fixed and we'll release a new version :)
